name: CompatHelper

on:
  schedule:
    - cron: '00 * * * *'
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: Pkg.Registry.add(Pkg.RegistrySpec(url="http://github.com/crstnbr/TrebstRegistry"))
        run: julia -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="http://github.com/crstnbr/TrebstRegistry"))'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main(;
                                                              registries = Pkg.Types.RegistrySpec[
                                                                  Pkg.RegistrySpec(
                                                                      name = "General",
                                                                      uuid = "23338594-aafe-5451-b93e-139f81909106",
                                                                      url = "https://github.com/JuliaRegistries/General.git"),
                                                                  Pkg.RegistrySpec(
                                                                      name = "TrebstRegistry",
                                                                      uuid = "df7bba20-026d-11ea-1ecb-03517e44f23d",
                                                                      url = "https://github.com/crstnbr/TrebstRegistry.git")
                                                                  ]
                                                              )'
